FROM ubuntu:20.04


RUN apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends --no-install-suggests \
       git \
       python3 \
       build-essential \
       chrpath \
       cpio \
       diffstat \
       file \
       gawk \
       wget
