#!groovy​

node('Linux') {
    stage('Clone sources') {
        checkout scm
    }

    def image = null
    stage('Build docker image') {
        image = docker.build('meta-conan', '-f .ci/Dockerfile .')
    }

    stage('Validate Yocto layer') {
        validate: {
            image.inside {
                sh '''
                    WORKSPACE=${PWD}
                    runuser -u conan -- git clone --depth 1 git://git.yoctoproject.org/poky -b dunfell /tmp/poky
                    runuser -u conan -- git clone --depth 1 git://git.openembedded.org/meta-openembedded.git -b dunfell /tmp/meta-openembedded
                    cd /tmp/poky/
                    runuser -u conan -- . /tmp/poky/oe-init-build-env
                    cd /tmp/meta-openembedded
                    runuser -u conan -- yocto-check-layer -d --dependency meta-oe meta-python --with-software-layer-signature-check ${WORKSPACE}
                '''
            }
        }
    }
}
