name: yocto_check_layer
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      YOCTO_RELEASE: dunfell
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: "Install APT packages"
        run: sudo apt-get install -y --no-install-recommends diffstat
      - name: "Setup Yocto layers"
        run: |
          mkdir /tmp/yocto
          git clone --depth 1 git://git.yoctoproject.org/poky -b ${YOCTO_RELEASE} /tmp/yocto/poky
          git clone --depth 1 git://git.openembedded.org/meta-openembedded.git -b ${YOCTO_RELEASE} /tmp/yocto/poky/meta-openembedded
      - name: "Validate Yocto layers"
        working-directory: /tmp/yocto
        run: |
          source poky/oe-init-build-env
          cd /tmp/yocto/poky/meta-openembedded
          yocto-check-layer -d --dependency meta-oe meta-python --with-software-layer-signature-check ${GITHUB_WORKSPACE}
