name: yocto_check_layer
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      YOCTO_RELEASE: dunfell
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: "Setup"
        run: |
          mkdir /tmp/yocto
          git clone git://git.yoctoproject.org/poky -b ${YOCTO_RELEASE} /tmp/yocto/poky
          git clone https://github.com/openembedded/meta-openembedded.git -b ${YOCTO_RELEASE} /tmp/yocto/poky/meta-openembedded
      - name: "Validate Yocto layers"
        working-directory: /tmp/yocto
        run: |
          source poky/oe-init-build-env
          yocto-check-layer -d --dependency meta-openembedded/meta-oe meta-openembedded/meta-python --with-software-layer-signature-check ${GITHUB_WORKSPACE}
